### ISSUE TITLE
Sandstorm: Possessed buttons do not return to default state

### ISSUE THREAD

**Issue by sreffler** [Mercury1089/2019-scouting-app#1]
**Expected result:** When tapping any of the following: a circle on the scoring diagram, the dropped button, or the missed button, the possessed button returns to its default state.

**Actual result:** When tapping a circle on the scoring diagram, the possessed button stays active (orange). 

_Note: This is NOT just a style issue, as the cargo possessed button is disabled while the panel possessed button is active, preventing a user from logging a possessed cargo if a robot picks one up._

**Comment by aschimmichanga** [comment]
Works as expected (returns to default state when dropped/missed or position on scoring diagram is selected)
