### ISSUE TITLE
Settings: Cancel button clears all stored values when reset button is active

### ISSUE THREAD

**Issue by sreffler** [Mercury1089/2019-scouting-app#10]
**Expected result:** When enabled and tapped,
- If any button states have changed, the changed buttons revert to their previous states (state before the Settings panel was opened) and the settings screen is closed.
- If NO button states have changed, the settings screen is closed.

**Actual result:** When the "Reset local variables" button is tapped and then the Cancel button is tapped, all values/variables are reset and the settings screen is closed.

_Note: See related issue Cancel button not disabled for expected on load state: https://github.com/Mercury1089/2019-scouting-app/issues/6_

**Comment by aschimmichanga** [comment]
Works as expected
