### ISSUE TITLE
Climbing: Changing states of buttons does not return user to step in flow as expected

### ISSUE THREAD

**Issue by sreffler** [Mercury1089/2019-scouting-app#103]
**Expected state:** 
Changing the state of a button, detects the state of other buttons and deselects/disables buttons that are "later" in the flow than the changed button. 

Tapping a selected button again deselects and restore default/disabled sates (as if they were never selected).

**Actual state:**
1. If "YES," "1," "YES," and "1" are selected, tapping "2" deselects and disables lift partners "YES/NO" as expected. But "1/2" partners does not deselect nor disable. Tapping "1" or "2" fixes the issue.

2. If "YES," "2" or "3," and "with Help" are selected, tapping level "2" or "3" (change state, not repeat tap), deselects and disables "1/2" partners, but the QR code does not enable. Tapping "on their own" or level "1" fixes the issue.

3. If "YES," "2," "YES," and "1" are selected, tapping "1" for level, deselects and disables "1/2" partners as expected, but lift "Y/N" does not deselect nor disable. Tapping lift "Y/" fixes the issue.

4. If "YES," "2," "ON THEIR OWN," "YES," and "1/2" are selected, tapping level "3," deselects and disables lift "Y/N" as expected, but "ON THEIR OWN/WITH HELP" does not deselect nor disable. Neither does "1/2" partners. Tapping "ON THEIR OWN/WITH HELP" fixes the issue. 

_Note: Each tap must check the state of all buttons,_

**Comment by aschimmichanga** [comment]
Works as expected
