### ISSUE TITLE
Sandstorm: Missing possessed, dropped, missed data in QR

### ISSUE THREAD

**Issue by sreffler** [Mercury1089/2019-scouting-app#104]
**Expected result:** Scanning a QR code AT MINIMUM creates event strings for possessed, missed, and dropped, for each game element.

**Actual result:** Possessed, missed, and dropped for each game element are no longer generating as part of the QR string.

**Comment by sreffler** [comment]
Seems inconsistent, some taps on the scoring circles seem to generate the possessed, missed, dropped, but not all.

**Comment by aschimmichanga** [comment]
Works as expected

**Comment by aschimmichanga** [comment]
Works as expected
