### ISSUE TITLE
Sandstorm & Teleop: Undo button does not undo missed or dropped.

### ISSUE THREAD

**Issue by RevanthRS** [Mercury1089/2019-scouting-app#109]
Expected Result: Undoes last recorded value (if missed was the last action, tapping "undo" should decrease the "missed" counter by 1 and reselect the appropriate game element; same for dropped).

Actual Result: Tapping "undo" disables the undo button as expected, but does not decrease the counter for either "missed" or "dropped" and does not reselect the appropriate game element. The "panel" and "cargo" buttons remain disabled and the user can only tap the "missed" or "dropped" button that was just undone.

**Comment by aschimmichanga** [comment]
Works as expected
