### ISSUE TITLE
Settings: Save button disabled when no states have changed

### ISSUE THREAD

**Issue by sreffler** [Mercury1089/2019-scouting-app#11]
**Expected result:** When accessing Settings via the Settings button, the save button is enabled (because at least one field side value is active and stored). When tapping the save button,
- If a field side button state has changed: the newly selected field side value (LEFT/RIGHT) is stored, and the settings screen is closed.
- If the reset button state has changed: all stored variables/values are cleared, all active states (throughout the entire app) are cleared, a toast notification is displayed that says "All variables successfully reset.", and the save and cancel buttons are disabled.
- If no states have changed, the settings screen is closed (works like a cancel button).

**Actual result:** When accessing Settings via the Settings button, the save button is disabled (and no field side value is active) until a user chooses a field side value/taps the rest button again.

_Note: The settings screen does not close after variables/values are reset, as user will need to choose a field side value again before they can proceed to the setup screen._

**Comment by aschimmichanga** [comment]
Works as expected

**Comment by aschimmichanga** [comment]
Works as expected
