### ISSUE TITLE
Settings: Cancel button clears stored field side

### ISSUE THREAD

**Issue by sreffler** [Mercury1089/2019-scouting-app#12]
**Expected result:** When accessing the Settings screen via the settings button, the last saved button state is displayed (e.g. if "left" was saved/stored, "left" should be active the next time the user opens the settings screen). 

When the cancel button is tapped,
- If any button states have changed: the changed buttons revert to their previous states (state before the Settings panel was opened) and the settings screen is closed
- If NO button states have changed, the settings screen is closed -- no values are cleared nor updated.

**Actual result:** When accessing the Settings screen via the settings button, no active field side value is displayed, and tapping the cancel button clears the stored field side value.

To recreate: 
1. Launch the app.
2. Select "LEFT" and tap "Save"
3. Tap the "Blue" alliance color button to see the blue platform display on the left side of the screen.
4. Tap the settings button
5. Tap cancel.
6. Tap the "blue" button again -- no platform is displayed because the app does not know what side to display.

**Comment by Arnavpmr** [comment]
This bug has been fixed and the cancel button works properly
