### ISSUE TITLE
Setup: Match number input field has the wrong keyboard

### ISSUE THREAD

**Issue by sreffler** [Mercury1089/2019-scouting-app#13]
**Expected result:** When tapped alphanumeric keyboard is opened (so users can enter, for example, "QF 4-1").
**Actual result:** Numeric-only keyboard is opened.

**Comment by aschimmichanga** [comment]
now has alphanumeric keyboard and match number is stored as a string

**Comment by Adog64** [comment]
This still is only numeric

**Comment by aschimmichanga** [comment]
it is supposed to be numeric lol
