### ISSUE TITLE
Setup: Clear button doesn't work

### ISSUE THREAD

**Issue by sreffler** [Mercury1089/2019-scouting-app#14]
**Expected result:** Button is disabled until at least one input field has been populated or one button has been selected. Once enabled, when tapped, opens a confirmation popup.

**Actual result:** Button is permanently disabled.

_Note: If this cannot be addressed by our first district, let's hide this button so users don't try to tap it._

**Comment by aschimmichanga** [comment]
works as expected

**Comment by Adog64** [comment]
clear button is still disabled until a value is changed.
