### ISSUE TITLE
Setup: No show toggle does not update visual display for prepop buttons/starting location diagram

### ISSUE THREAD

**Issue by sreffler** [Mercury1089/2019-scouting-app#15]
**Expected result:** When active (on),
- prepopulated buttons (PANEL/CARGO) are disabled (functionally and visually) and their supporting instructional text is grayed out
- starting position diagram is disabled (functionally and visually) and its supporting instructional text is grayed out
- start button is replaced by a “Generate QR” button

**Actual result:** When active (on),
- prepopulated buttions (PANEL/CARGO) are disabled, but have no visual cue
- supporting instructional text is grayed out all the time (regardless of no show toggle state)
- starting position diagram is hidden 
- supporting instructional text for starting position remains white
- start button is replaced by a “Generate QR” button

_Note: Functionally, this works as expected. The map is disabled (hidden), and the prepopulated buttons are disabled. Visual "disabled" styling on prepop buttons and starting location diagram is missing, which helps cue the user to the change._

**Comment by Arnavpmr** [comment]
loading screen is there

**Comment by Arnavpmr** [comment]
works as expected

**Comment by aschimmichanga** [comment]
Instead of putting the diagram in a disabled state, there is a message that is displayed in place of the diagram that says "Scoring diagram is unavailable because the robot did not show up" if the No Show switch is turned on.
