### ISSUE TITLE
Setup: Changing alliance color doesn't disable Start button

### ISSUE THREAD

**Issue by sreffler** [Mercury1089/2019-scouting-app#16]
**Expected result:** If a user changes alliance colors AFTER selecting a starting location, the starting location is cleared and the start button is disabled. User must select a starting location on the new diagram.

**Actual result:** The starting location on the incorrect diagram is stored, and the start button stays active. (This means a user can start the match, providing an incorrect starting location.)

To recreate:
1. Tap "Red"
2. Tap any location on the starting position map
3. Tap "Blue"
4. Tap "Start"
5. In the Sandstorm screen, tap "Setup" -- you should see an orange dot floating on the opposite side of the screen from the platform.

**Comment by aschimmichanga** [comment]
Works as expected

**Comment by sreffler** [comment]
Wasn't actually fixed -- worked with Arnav at 5:30 Mar 4 to correct.

**Comment by sreffler** [comment]
Still an issue, changing an alliance color displays a blank platform BUT the starting button is still enabled.

**Comment by aschimmichanga** [comment]
starting button disables whenever you click red or blue
