### ISSUE TITLE
Sandstorm: Possessed cargo button enables panel scoring locations

### ISSUE THREAD

**Issue by sreffler** [Mercury1089/2019-scouting-app#17]
**Expected result:** Tapping the cargo button enables the cargo scoring locations.
**Actual result:** Tapping the cargo button enables the panel scoring locations.

_Note: Cargo scoring locations are correctly enabled if the user chose cargo for prepop on the Setup screen._

**Comment by Arnavpmr** [comment]
When Cargo/Panel Buttons are selected, their appropraite buttons are now enabled in sandstorm
