### ISSUE TITLE
Setup: No show toggle doesn't hide/disable generate QR button

### ISSUE THREAD

**Issue by sreffler** [Mercury1089/2019-scouting-app#18]
**Expected result:** If the no show toggle is set to 0 (off), the QR button is disabled and hidden.

**Actual result:** If the no show toggle was set to 1 (on), then set back to 0 (off), the Start button is displayed, but tapping it generates a QR code. 

_Note: Suspect the QR button is hidden but still enabled._

**Comment by aschimmichanga** [comment]
works as expected
