### ISSUE TITLE
Sandstorm: Dropped button doesn't work

### ISSUE THREAD

**Issue by sreffler** [Mercury1089/2019-scouting-app#19]
**Expected result:** Once enabled, when tapped, 
- the button is temporarily marked “active” (changes color ~500ms) to indicate selected option
- the badge/counter inside the dropped button increases by one
- the missed button, dropped button, and scoring diagram are disabled
- If the possessed CARGO button is active,
-- the active possessed CARGO button is returned to its default state
-- the value of the sandstormDroppedCargo variable is increased by 1
- If the possessed PANEL button is active,
-- the active possessed PANEL button is returned to its default state
-- the value of the sandstormDroppedPanel variable is increased by 1

**Actual result:** Button is never enabled. Tapping it does nothing.

**Comment by aschimmichanga** [comment]
works as expected
