### ISSUE TITLE
Sandstorm: Possessed buttons allow for multiple possessions without scoring/dropping/missing 

### ISSUE THREAD

**Issue by sreffler** [Mercury1089/2019-scouting-app#2]
**Expected result:** Once a possessed button is active, it is also disabled and tapping it has no effect until the user has performed a qualifying secondary action. Qualifying actions: Tapping a scoring location, the missed button, or the dropped button.

**Actual result:** Once a possessed button is active, the user can tap it again immediately to add another possession.

**Comment by aschimmichanga** [comment]
once selected, panel/cargo buttons are disabled until someone scores/drops/misses
