### ISSUE TITLE
Setup: Generate QR button only enables when the BLUE button is active

### ISSUE THREAD

**Issue by sreffler** [Mercury1089/2019-scouting-app#20]
**Expected result:** When the no show toggle is set to 1 (on), the Start button is replaced by a “Generate QR” button. Generate QR button is enabled once scouter name, match number, team number, alliance partners, and alliance color are populated/selected (regardless of order in which they were completed).

**Actual result:** Generate QR code button is displayed, but is not enabled unless the user selects "BLUE" as an alliance color, AND toggles the no show toggle to 1 afterwards.

To recreate:
1. Complete the scouter name, match number, team number, and alliance partner fields.
2. Tap the no show button
3. Tap "RED" or "BLUE"

Some additional related states:
1. If all other fields/buttons are selected BEFORE the no show toggle is set to active, and the BLUE button is selected, the generate QR code button works as expected.
2. If a user selects "RED" then toggles to BLUE, then toggles the no show button off and back on, the QR button works as expected. 
3. If a user toggles the no show button off, selects BLUE, then toggles the no show button on, the QR button works as expected.
4. If a user toggles the no show button off, selects RED, then toggles the no show button on, the QR button DOES NOT work.

_Note: Issue appears to be specific to the RED button?_

**Comment by sreffler** [comment]
Additional related issue: If a user taps "BLUE," then sets the no show toggle to 1 (on), then taps the "Generate QR" button, the app crashes.

**Comment by Arnavpmr** [comment]
I fixed the bug, now the QRButton is only enabled when you fill out all the textboxes and select an alliance color along with flipping the noshow switch
