### ISSUE TITLE
Sandstorm: Possessed button is active even when nothing was prepopulated

### ISSUE THREAD

**Issue by sreffler** [Mercury1089/2019-scouting-app#22]
**Expected result:** If no game element is prepopulated in setup, Sandstorm starts with NO possessed buttons active (orange).

**Actual result:** If a prepop element was selected and THEN deselected so that NO prepop buttons are active, Sandstorm starts with a possessed button active, that matches whichever prepop button was last active, and the counter of that button is set to 1.

To recreate:
1. Complete the setup screen
2. Tap PANEL as the prepop object
3. Tap PANEL again to deselect it
4. Tap the Start button
5. PANEL button is active (and panel scoring locations) are active in Sandstorm

**Comment by Arnavpmr** [comment]
Bug is patched, when user selects no starting game element, no buttons will be active
