### ISSUE TITLE
Setup: Input fields are hard to see

### ISSUE THREAD

**Issue by sreffler** [Mercury1089/2019-scouting-app#23]
**Expected result:** Traditional input field styling (white box with light gray border)
**Actual result:** Black line on a dark background

<img width="311" alt="screen shot 2019-02-26 at 5 37 04 pm" src="https://user-images.githubusercontent.com/8864777/53451593-2ad2c800-39ed-11e9-99fd-304b88353efa.png">

**Comment by aschimmichanga** [comment]
Is now a white textbox

**Comment by aschimmichanga** [comment]
Is now a white textbox

**Comment by aschimmichanga** [comment]
is a white textbox now
