### ISSUE TITLE
Sandstorm: Scoring diagram, not all circles disabled

### ISSUE THREAD

**Issue by sreffler** [Mercury1089/2019-scouting-app#26]
**Expected result:** On screen load, all circles are disabled.
**Actual result:** "CargoShip Panel Left 2" and "CargoShip Panel Left 3" circles can be scored, even if no possession has been marked.

To recreate:
Complete the setup screen but DO NOT select "PANEL" or "CARGO"
2. Tap the start button
3. Tap the Cargo Ship Left 2, and Cargo Ship Left 3 scoring locations.

**Comment by aschimmichanga** [comment]
works as expected
