### ISSUE TITLE
Sandstorm: Fell over toggle still allows scoring

### ISSUE THREAD

**Issue by sreffler** [Mercury1089/2019-scouting-app#27]
**Expected result:** When active (on),
- possessed buttons (PANEL/CARGO) are disabled (functionally and visually) and their supporting instructional text is grayed out
- DROPPED and MISSED buttons are disabled (functionally and visually) 
- scoring location diagram is disabled (functionally and visually) and its supporting instructional text is grayed out

**Actual result:** When active (on),
* possessed buttons (PANEL/CARGO) are disabled, but have no visual cue
* scoring location diagram is still enabled

Note: Please prioritize the FUNCTIONAL issue of the scoring diagram before addressing the visual issues of the PANEL/CARGO buttons.

**Comment by Arnavpmr** [comment]
This bug, is patched, fell over switch now disables diagram and appropriate buttons when toggled and re-enables them if toggled off

**Comment by sreffler** [comment]
Works as expected for everything EXCEPT HAB Line toggle. User can still toggle HAB line on/off even when fell over toggle is on.

**Comment by aschimmichanga** [comment]
works as expected, although there is still no disabled styling
