### ISSUE TITLE
Sandstorm: Undo button does not work

### ISSUE THREAD

**Issue by sreffler** [Mercury1089/2019-scouting-app#28]
**Expected result:** On screen load, the button is disabled. It is enabled after a user has completed an action on the Sandstorm screen. When tapped, the user’s last action is reversed and the undo button is disabled (and waits for another action to re-enable). 

**Actual result:** 
1. Undo button never disables.
2. User can undo multiple actions.
3. User can undo beyond actions they've completed (example: if you tap 10 times on the Panel button, then tap undo 11 times, you get -1 panels). 
4. When HAB line toggle is on (1), tapping undo toggles the HAB line toggle repeatedly and scoring is permanently disabled.
5. Changes the color of a scoring location but does not decrease the counter.

**Comment by aschimmichanga** [comment]
works as expected (except instead of P or C, 0 is just displayed)
