### ISSUE TITLE
Settings: Current stored field side value is not displayed (no active button state)

### ISSUE THREAD

**Issue by sreffler** [Mercury1089/2019-scouting-app#3]
**Expected result:** When opening Settings from setup (via the settings button), the last saved button state is displayed.
**Actual result:** When opening the Settings screen from setup, neither the left nor right button is displayed active (regardless of which the user previously saved).

_Note: It's not clear whether the field side value is stored correctly and the Settings screen is just not checking for it and displaying the corresponding active button style, or if the value is not being stored correctly._

To recreate:
1. Open the app and select and save a field side.
2. Open the settings screen via the settings button.

**Comment by aschimmichanga** [comment]
works as expected
