### ISSUE TITLE
Setup: Starting location diagram, missing error message view

### ISSUE THREAD

**Issue by sreffler** [Mercury1089/2019-scouting-app#31]
**Expected result:** On initial app load, diagram is disabled and covered by error message until a user has selected both a field side option in the settings screen and an alliance color on the setup screen.

**Actual result:** Starting location diagram is hidden with no context for user until both field side and alliance color are selected.

_Note: Functionally, this works okay, but it would be useful to give the user context that there is an unavailable item they need to complete._

**Comment by aschimmichanga** [comment]
Although there is no disabled diagram shown, there is an error message that spans the entire space. It appears when you first open up the screen and there is no prepopulate blue/red or deselect a button.
