### ISSUE TITLE
Setup: HAB platform display is backwards

### ISSUE THREAD

**Issue by sreffler** [Mercury1089/2019-scouting-app#32]
New issue as of commit from @Arnavpmr on Tues, 2/26 6:31pm:

**Expected result:** Based on the field side and alliance color values, 4 views are possible:
- If “LEFT” and “BLUE” are selected, a diagram with the blue platform on the left side of the screen will display.
- If “RIGHT” and “BLUE” are selected, a diagram with the blue platform on the right side of the
screen will display.
- If “LEFT” and “RED” are selected, a diagram with the red platform on the right side of the screen will display.
 - If “RIGHT” and “RED” are selected, a diagram with the red platform on the left side of the screen
will display.

**Actual result:** 
- If LEFT is selected: BLUE and RED are both on the right side of the screen
- If RIGHT is selected: BLUE and RIGHT are both on the left side of the screen

**Comment by sreffler** [comment]
Related: when tapping "SETUP" from the Sandstorm screen, the correct view of the starting location diagram is shown.

**Comment by aschimmichanga** [comment]
works as expected

**Comment by sreffler** [comment]
From latest pull, 2:31pm Sat Mar 2, issue is still persistent.

**Comment by aschimmichanga** [comment]
fixed, works as expected
