### ISSUE TITLE
Sandstorm: Reset countdown timer if user returns to Setup

### ISSUE THREAD

**Issue by sreffler** [Mercury1089/2019-scouting-app#33]
**Expected result:** User taps the Setup button on the Sandstorm screen, is returned to the Setup screen, and the countdown timer is reset to 15s. Countdown begins again when the user taps the start button/the sandstorm screen is loaded.
**Actual result:** The timer continues to countdown regardless of location in the app.

_Note: During testing we realized that there may be cases where a user accidentally hits start too soon (before the actual match starts), and we don't want them to be advanced to teleop before teleop actually starts. 

We recognize that there is risk of the opposite being true as well (teleop values accidentally captured in sandstorm), but believe this risk to be smaller.

Please also note this countdown issue is specific to Sandstorm > Setup, the countdown should NOT reset if a user switches back and forth from Teleop > Sandstorm or Climbing > Sandstorm._

**Comment by aschimmichanga** [comment]
works as expected
