### ISSUE TITLE
Sandstorm/Setup: Values and states of sandstorm not stored

### ISSUE THREAD

**Issue by sreffler** [Mercury1089/2019-scouting-app#34]
**Expected result:** If a user taps the Setup button on the Sandstorm screen, then taps the Start button (to return to Sandstorm), any values/states that were previously entered on the Sandstorm screen (at the time when the user tapped Setup) are visible.

**Actual result:** If a user taps the Setup button on the Sandstorm screen, then taps the Start button (to return to Sandstorm), all values and states of the screen are reset. 

Example: 
1. User completes the setup screen and starts the match
2. Their robot's prepopulated panel is scored on the front of the cargo ship. 
3. User taps the "Sandstorm,CargoShip,Panel,Front,,1" circle.
-- the circle turns yellow, the counter is increased to 1, 
-- the scoring location diagram is disabled, dropped and missed buttons are disabled, 
-- the possessed button is returned to its default state
4. User realizes they made a mistake on the setup screen, and need to change the number of their alliance partner, so they tap the setup button to return to setup. 
5. They fix the mistake and press start again. 
6. When the Sandstorm screen loads, 
-- "Teleop,CargoShip,Panel,Front,,1" is yellow but disabled, the counter is set to 1, 
-- the scoring location diagram is disabled, dropped and missed buttons are disabled, 
-- the possessed buttons are both in their default state

**Comment by aschimmichanga** [comment]
works as expected

**Comment by Adog64** [comment]
not resolved

**Comment by sreffler** [comment]
Also an issue for returning to Sandstorm from Climbing

**Comment by sreffler** [comment]
Superceded by issue #80, however after resolving 80, will need to test that HAB line toggle, fell over toggle, and possessed active state (and counter) return as expected.

**Comment by aschimmichanga** [comment]
Works as expected
