### ISSUE TITLE
Sandstorm screen is not prepopulated when you go back to it from the Climb screen

### ISSUE THREAD

**Issue by aschimmichanga** [Mercury1089/2019-scouting-app#39]
Expected: All populated values should stay the same when returning to the Sandstorm screen from other screens.

Actual: Every time you open the Sandstorm screen, it appears as if you came to the Sandstorm screen for the first time from the Setup screen.

**Comment by aschimmichanga** [comment]
cannot be done until Sandstorm tags are finalized

**Comment by sreffler** [comment]
Superceded by issue #83. No longer relevant.
