### ISSUE TITLE
Sandstorm: scoring diagram, always enabled

### ISSUE THREAD

**Issue by sreffler** [Mercury1089/2019-scouting-app#4]
**Expected result:** Once a scoring diagram circle is tapped, the scoring diagram is disabled until another element is possessed (and a possession button is active).

**Actual result:** Tapping on any scoring diagram circle logs that element scored, regardless of whether they have possessed that number of objects or not. 

(This means a user can mark that their robot scored 5 panels, even though it only possessed 1).

Related issue: Possessed buttons do not return to default state https://github.com/Mercury1089/2019-scouting-app/issues/1

**Comment by aschimmichanga** [comment]
Now becomes entirely disabled as soon as a user tapped a button, and only certain parts of the diagram are enabled depending on whether panel or cargo is tapped
