### ISSUE TITLE
Climbing: All buttons to work, when "NO" is selected

### ISSUE THREAD

**Issue by Ramjazz** [Mercury1089/2019-scouting-app#47]
**Expected result:** Tapping "NO" enables the QR button, and disables all other buttons. 
**Actual result:** Tapping "NO" doesn't disable anything.

**Comment by aschimmichanga** [comment]
This was already resolved. Are you testing an outdated version of the app? @Ramjazz

**Comment by aschimmichanga** [comment]
In order to confirm, I just tested on a tablet with the latest version of the app on it.

**Comment by aschimmichanga** [comment]
works as expected
