### ISSUE TITLE
Settings: Tapping "Save" in Settings after a match (with at least one field completed) crashes the app

### ISSUE THREAD

**Issue by Arnavpmr** [Mercury1089/2019-scouting-app#48]
**Expected result:** The settings screen should not be affected by the setup screen, and having fields filled out prior to resetting the side blue is on after a match should not crash the app

**Actual result:** Having fields filled out before going into settings, then going into settings and resetting the side crashes the app.

_Note: Went through a match, got the QR code, was sent back to the setup screen(as should happen), filled out first field and then went back into settings to reset the side, clicked left and then save and the app crashed_

**Comment by sreffler** [comment]
There shouldn't likely be an instance where this happens -- as field side should be set once at the beginning of the day, so please prioritize other issues over this one.

**Comment by aschimmichanga** [comment]
works as expected
