### ISSUE TITLE
Sandstorm: Scoring diagram broken button (left rocket, panel, near, T3)

### ISSUE THREAD

**Issue by sreffler** [Mercury1089/2019-scouting-app#5]
**Expected result:** When tapped, counter inside the button increases by one. If button was in its default "0" state, changes to a scored state (bright yellow), and scoring diagram is then disabled. 

**Actual result:** Crashes the app when tapped.

**Comment by aschimmichanga** [comment]
Works as expected (just like the other scoring buttons)
