### ISSUE TITLE
Settings: After a match, the field side value is being reset/not detected, causing the app to crash

### ISSUE THREAD

**Issue by sreffler** [Mercury1089/2019-scouting-app#50]
**Expected result:** After generating a QR code, and returning to Setup, tapping an alliance color button generates the starting location diagram (using the previously selected field side to identify placement).

**Actual result:** After generating a QR code, and returning to Setup, tapping an alliance color button crashes the app.

_Note: Field side value is apparently not being read/stored correctly, so on returning to Setup, the diagram doesn't know what to load and is causing a crash._

**Comment by aschimmichanga** [comment]
works as expected
