### ISSUE TITLE
Sandstorm: "Starting soon" option displaying at the wrong time.

### ISSUE THREAD

**Issue by jal000** [Mercury1089/2019-scouting-app#52]
**Expected Result:**  It should happen at the last 3 seconds

**Actual Result:** "Starting soon" displays at the beginning of and throughout all of Sandstorm

**Comment by aschimmichanga** [comment]
the reason for starting soon is so that we will not have to update the UI later. The UI cannot be updated in two places at once in Android Studio, which is why we did "Starting Soon". Doing as you wish would not let users enter anything in the last three seconds before teleop.
