### ISSUE TITLE
Sandstorm: Selecting and deselecting Fell Over allows user to score objects even if there is no possession

### ISSUE THREAD

**Issue by RevanthRS** [Mercury1089/2019-scouting-app#56]
Expected Result: Selecting and deselecting Fell Over only enables/disables buttons that were enabled prior to the selection of Fell Over

Actual Result: After toggling Fell Over back to inactive, all scoring options are enabled, regardless of whether or not a Panel or Cargo was possessed prior to the selection of Fell Over

Note: Both Panel and Cargo scoring options are enabled, Missed and Dropped are not.

**Comment by aschimmichanga** [comment]
if the fell over switch is turned on and then off, the entire scoring diagram is disabled until you select panel/cargo
