### ISSUE TITLE
Sandstorm: The scoring diagram does not flip to reflect the side chosen

### ISSUE THREAD

**Issue by RevanthRS** [Mercury1089/2019-scouting-app#57]
Expected Result: The scoring diagram should reflect the chosen side that Blue is on, as well as the chosen alliance color

Actual Result: The scoring diagram always faces as though the diagram chosen was one where the HAB Platform is on the left side of the field

Note: For example, if Blue is on the right, and you choose Blue, the field(the front of the cargo ship) should be facing the right, however right now it is facing to the left.

**Comment by sreffler** [comment]
More important to get a single side working fully through an entire match than having 2 views. We can add the second view later.

**Comment by aschimmichanga** [comment]
There will be a separate screen for if it is on the right or left side. However, because the code will be exactly the same, the Right Sandstorm screen will only be implemented once the Left Sandstorm screen is done.

**Comment by aschimmichanga** [comment]
Works as expected
