### ISSUE TITLE
Sandstorm: When you go back to Sandstorm after it is over, there is no yellow border to caution you

### ISSUE THREAD

**Issue by RevanthRS** [Mercury1089/2019-scouting-app#58]
Expected Result: If you are in Tele-Op and go back into Sandstorm, a yellow border should appear to signify that you need to go back to Tele-Op as soon as possible and a toast notification should appear(saying "Teleop has started. Advance to Teleop as soon as possible."

Actual Result: No warning is displayed

**Comment by aschimmichanga** [comment]
There will be a maroon background as a warning instead of a yellow border.
