### ISSUE TITLE
Setup: Should require Panel/Cargo to be selected to enable Start button

### ISSUE THREAD

**Issue by aschimmichanga** [Mercury1089/2019-scouting-app#59]
The app crashes because of a null pointer exception when you don't select Panel/Cargo.

**Comment by aschimmichanga** [comment]
Works as expected

**Comment by Adog64** [comment]
Panel/Cargo should not be required.

**Comment by sreffler** [comment]
This is not an issue, but has now created a new one. 

User does NOT need to select panel/cargo to start a match, as a robot is NOT required to start with a game element.

If the app will not work without something being selected, we need to add a "NONE" button.

**Comment by aschimmichanga** [comment]
We have to add a none button, because not having panel/cargo creates a null pointer exception

**Comment by aschimmichanga** [comment]
is not required anymore, doesn't crash
