### ISSUE TITLE
Settings: Cancel button not disabled

### ISSUE THREAD

**Issue by sreffler** [Mercury1089/2019-scouting-app#6]
**Expected result:** On initial app load, cancel button is disabled. 
**Actual result:** Cancel button is always enabled. User can close the Settings screen without ever choosing a field side.

_Note: Cancel button is enabled only after user has successfully saved a field side value, and returns to settings via the Settings button on the Setup screen._

**Comment by aschimmichanga** [comment]
works as expected (cannot cancel until a side is saved at least once)
