### ISSUE TITLE
Setup: 2nd alliance partner field not part of form group

### ISSUE THREAD

**Issue by sreffler** [Mercury1089/2019-scouting-app#64]
**Expected:** From the 1st alliance partner field, tapping the green "next/ok" button on the keyboard, advances the user to the 2nd alliance partner field.

**Actual:** Tapping the green "next/ok" button on the keyboard, does not advance the user to the 2nd alliance partner field. It closes the keyboard.

_Note: Seems like maybe that input field is not part of the "form group," so the keyboard thinks all the fields are complete?_

**Comment by aschimmichanga** [comment]
works as expected
