### ISSUE TITLE
Setup: Event Listener issues related to start button

### ISSUE THREAD

**Issue by sreffler** [Mercury1089/2019-scouting-app#66]
Expected: All required fields are complete and Start  button is enabled
Actual: Sometimes the start button doesn't enable, unless a user goes back and reenters a field.

To recreate:
1. Enter something in all form fields
2. Tap an alliance color.
3. Tap a starting position.
4. Start is disabled. 

_Note: Logic is seeing a field as empty, possibly?_

**Comment by sreffler** [comment]
Aidan also found some situations where the Start button is enabled when fields are missing, specifically it seems like starting location is no longer required.

**Comment by aschimmichanga** [comment]
works as expected... only needs all text fields and color to enable start button
