### ISSUE TITLE
Setup: Clear button opens confirmation popup

### ISSUE THREAD

**Issue by sreffler** [Mercury1089/2019-scouting-app#67]
**Expected:** Tapping the clear button opens a confirmation popup asking the user if they want to clear setup.
**Actual:** Setup is cleared

![setup clear](https://user-images.githubusercontent.com/8864777/53767777-cc9e5d00-3ea4-11e9-85c4-7da8224f018a.png)

**Comment by aschimmichanga** [comment]
works as expected
