### ISSUE TITLE
Setup: Clear button doesn't return starting location message

### ISSUE THREAD

**Issue by sreffler** [Mercury1089/2019-scouting-app#68]
**Expected:** Clearing the screen resets to its default state: all fields blank, all buttons default, all toggles off, and the area where the starting location diagram displays has a "You must select an alliance color before you can access the map.." message.

**Actual:** All fields, buttons, etc. reset as expected, but the starting location message does not display.

**Comment by aschimmichanga** [comment]
works as expected
