### ISSUE TITLE
Setup: Fell over toggle doesn't restore previous state

### ISSUE THREAD

**Issue by sreffler** [Mercury1089/2019-scouting-app#69]
**Expected:** Any buttons or scoring locations that were enabled and/or active when the fell over toggle was set to on, should be returned to their enabled/active states when the toggle is turned off (either by Undo button or by tapping the toggle).

**Actual:** Turning off the toggle, enables possession buttons, but does not restore active states nor enable the scoring diagram (which I suspect is tied to the active state function).

**To recreate:**
1. Start sandstorm with a panel in your possession
2. Tap the fell over toggle
3. Tap undo or the fell over toggle
4. Panel button is enabled, but not orange. No scoring diagram locations are enabled.

If the robot had a panel when they "fell over" they should still be able to score that panel if they are no longer "over."

**Comment by aschimmichanga** [comment]
works as expected
