### ISSUE TITLE
Settings: Save button (missing disabled style) 

### ISSUE THREAD

**Issue by sreffler** [Mercury1089/2019-scouting-app#7]
**Expected result:** The save button appears "grayed out," so it is obvious to the user that it is disabled.
**Actual result:** Appears in its "default" tappable state.

_Note: Functionally, it works as expected -- the user can tap on it and nothing happens._

**Comment by aschimmichanga** [comment]
Looks as expected

**Comment by sreffler** [comment]
Style is still default, does not ever display as disabled.

**Comment by aschimmichanga** [comment]
looks as expected (green/white when enabled, grey/dark grey when disabled)

**Comment by sreffler** [comment]
Still missing disabled visual style for the following scenarios:
- On initial app load (both Save and Cancel should be grey/dark gray)
- After reset local storage is successful, both Save and Cancel should be grey/dark grey

**Comment by aschimmichanga** [comment]
looks as expected
