### ISSUE TITLE
Setup/Climbing: Generate QR button opens confirmation popup

### ISSUE THREAD

**Issue by sreffler** [Mercury1089/2019-scouting-app#72]
**Expected result:** Tapping the Generate QR button opens a confirmation popup, where the user has to tap the "Generate QR Code" button to actually create a QR.

**Actual result:** Tapping the Generate QR button generates a QR code

![climbing confirm qr](https://user-images.githubusercontent.com/8864777/53772734-8ac9e280-3eb5-11e9-97f1-49e64cd010ea.png)

**Comment by aschimmichanga** [comment]
works as expected
