### ISSUE TITLE
Settings/Setup: App stops when going back to settings after completing no-show setup

### ISSUE THREAD

**Issue by Adog64** [Mercury1089/2019-scouting-app#73]
Expected: The app shouldn't crash

Actual: The app crashes

To recreate:

1. Complete the scouter name, match number, team number, and alliance partner fields.
2. Tap the no show button
3. Tap "RED" or "BLUE"
4. Go back to settings
5. Click "Save"

**Comment by aschimmichanga** [comment]
works as expected
