### ISSUE TITLE
Sandstorm/Teleop: Need to store key/value for any possessed objects that carry into teleop

### ISSUE THREAD

**Issue by sreffler** [Mercury1089/2019-scouting-app#77]
In setup, create a key/value pair for prepopTeleop, so we can detect in Tableau if a team was possessing a game element at the start of Teleop.

We think the best way to achieve this might be to set a variable to either "C" or "P," either at coundowntimer= 0 or on screen load of teleop, and output the value of that variable during QR generation.

**Comment by aschimmichanga** [comment]
works as expected
