### ISSUE TITLE
QR: Add confirmation popup to Set Up Next Match button

### ISSUE THREAD

**Issue by sreffler** [Mercury1089/2019-scouting-app#78]
**Expected result:** "Set Up Next Match" button is disabled until user turns on "QR code scanned" toggle
**Actual:** No toggle exists, button is enabled all the time

Note: We identified a need for this confirmation during training today (so that a QR isn't erased accidentally, and we capture all of our scouters' data).

![qr copy](https://user-images.githubusercontent.com/8864777/53846803-5b31dd80-3f7c-11e9-86b3-4a4aded61eff.png)
![qr](https://user-images.githubusercontent.com/8864777/53846804-5bca7400-3f7c-11e9-8568-4ec04587b147.png)

**Comment by aschimmichanga** [comment]
fixed via switch
