### ISSUE TITLE
Sandstorm: Pre-populated element is not automatically selected

### ISSUE THREAD

**Issue by RevanthRS** [Mercury1089/2019-scouting-app#79]
**Expected result:** When an element is selected as prepopulated on the setup screen, its corresponding possessed button is active on the Sandstorm screen, and its corresponding scoring locations are enabled.

**Actual result:** No buttons are active, regardless of whether the user prepopulated with a panel or cargo, the number for possessed is 0, and no scoring locations are enabled.

**Comment by aschimmichanga** [comment]
Works as expected

**Comment by sreffler** [comment]
Per duplicate issue logged 2 hours ago from Revanth, still persistent.

**Comment by aschimmichanga** [comment]
Works as expected
