### ISSUE TITLE
Settings: Save button disabled when "reset" button is active

### ISSUE THREAD

**Issue by sreffler** [Mercury1089/2019-scouting-app#8]
**Expected result:** After a user taps the "Reset Local Storage" button, the Save button is enabled. Then, tapping the save button clears all stored values/variables in the app, clears the "active" state of the reset button, displays a toast notification that says "All variables successfully reset.", and disables the save and cancel buttons.

**Actual result:** After a user taps the "Reset Local Storage" button, the Save button remains disabled (nothing happens when the Save button is tapped). 

_Note: It's possible that the Save button is working as expected, but there is no visual cue to tell the user anything happened._

**Comment by aschimmichanga** [comment]
works as expected

**Comment by sreffler** [comment]
As of latest build, 2:31pm Mar 2, issue is still persistent.

**Comment by aschimmichanga** [comment]
works as expected
