### ISSUE TITLE
Settings: Save button does not reset, when field side is selected and reset button is active

### ISSUE THREAD

**Issue by sreffler** [Mercury1089/2019-scouting-app#9]
**Expected result:** If any field side is selected and the "Reset local storage" button is selected, when user taps the Save button, 
a) all values are cleared, 
b) all active button states are cleared (both field side and reset buttons are returned to their default states),
c) a toast notification is displayed that says "All variables successfully reset.", and 
d) the save and cancel buttons are disabled.

**Actual result:** If field side is selected, and "Reset local storage" button is selected, and user taps the Save button, the settings screen is closed and the field side value is stored.

To recreate:
1. Tap the "Left" button
2. Tap the "Reset local storage" button
3. Tap the "Save" button

Note: Likely related to the "Save button disabled" issue: https://github.com/Mercury1089/2019-scouting-app/issues/8

**Comment by aschimmichanga** [comment]
Works as expected

**Comment by sreffler** [comment]
Per latest build, 2:31pm Mar 2, issue still persists. User can tap "Reset" button, but tapping "SAVE" does nothing. Tapping "Cancel" also does nothing.

**Comment by aschimmichanga** [comment]
works as expected
