### ISSUE TITLE
Setup: Generate QR code button does not enable when all required fields are populated/selected

### ISSUE THREAD

**Issue by sreffler** [Mercury1089/2019-scouting-app#94]
**Expected result:** Generate QR button enables only after all required fields are populated.
Required fields:
- Scouter Name
- Match #
- Team #
- Alliance color
- No show toggle on

**Actual result:**
- Requires alliance partners to be populated, which is not a requirement (does not need to be fixed at this time)
- Works as expected when it's the last thing tapped
- Does not enable QR code button if no show toggle is set to “on” before all other fields are populated. Toggling it off and back on fixes the problem. 
- If alliance color is changed after no show is toggled, button does not enable. Toggling it off and back on fixes the problem.

**Comment by sreffler** [comment]
Okay if not resolved before Mt. Olive

**Comment by aschimmichanga** [comment]
Works as expected
