### ISSUE TITLE
Climbing: Generate QR button enables before all requirements are met  

### ISSUE THREAD

**Issue by sreffler** [Mercury1089/2019-scouting-app#96]
**Expected result:** On screen load, check if the "Fell over" toggle was on during the Sandstorm/Teleop period. If toggle was set to "on" (1), QR button is enabled. If toggle was set to "off" (0), the "Did they end up on the HAB" buttons are enabled. 

Based on response to the "Did they end up on the HAB" question, additional questions are enabled:
1. If "NO" is selected, "Did they lift partners" question is enabled.
2. If "YES" is selected, the "What level" question is enabled.

Additional requirements cascade, based on responses to the above. 
Generate QR button is not enabled until all requirements are met. 

Minimum requirements to enable the QR button:
BOTH selected answers to "Did they end up on the HAB" and "Did they lift partners" are “NO.”

- If “Yes” is selected for “Did they end on the HAB”, selecting “1,” “2,” or “3” is also required.  
-- If “2” or “3” is selected, selecting “On their own” or “with help” is also required 
- If “Yes” is selected for “Did they lift any partners,” selecting “1” or “2” is also required

  **Actual result:**  All buttons are enabled on screen load. User does not need to answer any questions in order to generate a QR code.

Reference flowchart for expected enabled/disabled states:
![Screen Shot 2019-03-20 at 11 06 52 AM](https://user-images.githubusercontent.com/8864777/54696326-ff319200-4b01-11e9-9f41-2d8d639311d8.png)

**Comment by sreffler** [comment]
This MUST be fixed for Mt. Olive or we are unable to properly capture climbing data.

**Comment by sreffler** [comment]
Reference flowchart to resolve

![Screen Shot 2019-03-20 at 11 06 52 AM](https://user-images.githubusercontent.com/8864777/54695450-55053a80-4b00-11e9-8c63-a97a7c8f6be2.png)

**Comment by sreffler** [comment]
content of original issue updated to reflect latest build and new flowchart requirements.

**Comment by aschimmichanga** [comment]
Works as expected
